version: "3"
services:
  mongo:
    container_name: mongo_container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api_container
    build:
      context: .
      dockerfile: Dockerfile # Especifica o nome do Dockerfile a ser usado
    restart: always
    volumes:
      - ./dist/:/usr/clean_node_api_mango/dist/
      - ./package.json:/usr/clean_node_api_mango/package.json
    ports:
      - "3000:3000"
    depends_on:
      - "mongo"
